name: KeyFC Daily Record
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master

jobs:
  build:
    name: Record
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: '^1.14'

      - name: Build KeyFC
        run: sudo go build -o /usr/bin/keyfc ./

      - name: Checkout public
        uses: actions/checkout@v2
        with:
          ref: 'public'

      - name: Run KeyFC Record
        run: keyfc -p record.json -chart record.png

      - name: Commit files
        run: |
          git config --local user.email "i@iochen.com"
          git config --local user.name "Richard Chen - GitHub Action"
          git add record.json record.png
          git commit -m "$(date)"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'public'
